kind: ConfigMap
apiVersion: v1
metadata:
  name: earth-data-sql
data:
  earth-data.sql: |-
    -- Create a new database called 'InternationalDB'
    -- Connect to the 'master' database to run this snippet
    USE master
    GO
    -- Create the new database if it does not exist already
    IF NOT EXISTS (
        SELECT name
            FROM sys.databases
            WHERE name = N'InternationalDB'
    )
    CREATE DATABASE InternationalDB
    GO
    -- Connect to the 'InternationalDB' database to run this snippet
    USE InternationalDB
    GO
    -- Create a new table called 'Orders' in schema 'dbo'
    -- Drop the table if it already exists
    IF OBJECT_ID('dbo.Orders', 'U') IS NOT NULL
    DROP TABLE dbo.Orders
    GO
    -- Create the table in the specified schema
    CREATE TABLE dbo.Orders
    (
        OrderId INT IDENTITY(1,1) NOT NULL PRIMARY KEY, -- primary key column
        OrderType [NVARCHAR](1) NOT NULL,
        OrderItemName [NVARCHAR](50) NOT NULL,
        Quantity INT NOT NULL,
        Price [NVARCHAR](50) NOT NULL,
        ShipmentAddress [NVARCHAR](100) NOT NULL,
        ZipCode [NVARCHAR](10) NOT NULL,
        OrderUser [NVARCHAR](10) NOT NULL
        -- specify more columns here
    );
    GO
    -- Enable Database for CDC template
    EXEC sys.sp_cdc_enable_db
    GO
    -- Enable a Table
    EXEC sys.sp_cdc_enable_table
    @source_schema = N'dbo',
    @source_name = N'Orders',
    @role_name = NULL,
    @supports_net_changes = 1
    GO

    DROP TABLE QUOTEEJB;
    GO
    DROP TABLE KEYGENEJB;
    GO
    DROP TABLE ACCOUNTEJB;
    GO
    DROP TABLE ORDEREJB;
    GO
    CREATE TABLE HOLDINGEJB
    (
        PURCHASEPRICE DECIMAL(14, 2),
        HOLDINGID INTEGER NOT NULL,
        QUANTITY DOUBLE NOT NULL,
        PURCHASEDATE TIMESTAMP,
        ACCOUNT_ACCOUNTID INTEGER,
    QUOTE_SYMBOL VARCHAR(250)
    );
    GO

    ALTER TABLE HOLDINGEJB
    ADD CONSTRAINT PK_HOLDINGEJB PRIMARY KEY (HOLDINGID);
    GO
    CREATE TABLE ACCOUNTPROFILEEJB
    (
        ADDRESS VARCHAR(250),
    PASSWD VARCHAR(250),
    USERID VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(250),
    CREDITCARD VARCHAR(250),
    FULLNAME VARCHAR(250));
    GO
    ALTER TABLE ACCOUNTPROFILEEJB
    ADD CONSTRAINT PK_ACCOUNTPROFILE2 PRIMARY KEY (USERID);
    GO
        OrderUser [NVARCHAR](10) NOT NULL
        -- specify more columns here
    );
    GO
    -- Enable Database for CDC template
    EXEC sys.sp_cdc_enable_db
    GO
    -- Enable a Table
    EXEC sys.sp_cdc_enable_table
    @source_schema = N'dbo',
    @source_name = N'Orders',
    @role_name = NULL,
    @supports_net_changes = 1
    GO

    DROP TABLE QUOTEEJB;
    GO
    DROP TABLE KEYGENEJB;
    GO
    DROP TABLE ACCOUNTEJB;
    GO
    DROP TABLE ORDEREJB;
    GO
    CREATE TABLE HOLDINGEJB
    (
        PURCHASEPRICE DECIMAL(14, 2),
        HOLDINGID INTEGER NOT NULL,
        QUANTITY DOUBLE NOT NULL,
        PURCHASEDATE TIMESTAMP,
        ACCOUNT_ACCOUNTID INTEGER,
    QUOTE_SYMBOL VARCHAR(250)
    );
    GO

    ALTER TABLE HOLDINGEJB
    ADD CONSTRAINT PK_HOLDINGEJB PRIMARY KEY (HOLDINGID);
    GO

